In [1]:
import re
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df = pd.read_csv(r'C:\Users\Checkout\Downloads\cyberbullying-classification-master\data\train_data.csv')

# printing the shape: (rows, columns)
display(df.shape)

# first 5 datapoints
display(df.head())

# 5 random samples
display(df.sample(5))

(28614, 2)

                                         clean_tweet   cyberbullying_type
0  hate ppl high school used bully hot omg love m...                  age
1                          kat andre asshole omg mkr    not_cyberbullying
2  new access trading cause need high level opini...                  age
3  fuck david duke racist think america belong du...            ethnicity
4  may say lot hate apologetic army hope choke ev...  other_cyberbullying

                                             clean_tweet   cyberbullying_type
14483  verdonmusic kam coastal thelandofblueharmonie ...               gender
19747  thing funny rape joke telling people kill gay ...               gender
21790                                price every process    not_cyberbullying
5457   elplatt mostly pondering startup incubator acc...  other_cyberbullying
9896   skawtnyc athenahollow twoscooters tend talk mu...    not_cyberbullying

In [3]:
cv = CountVectorizer()
counts = cv.fit_transform(df['clean_tweet'].values.astype('U'))

In [4]:
df_bow = pd.DataFrame(counts.A, columns=cv.get_feature_names())
df_bow['cyberbullying_type'] = df['cyberbullying_type']

In [7]:
df_bow

,aaa,aaaa,aaaaaaaaaa,aaaaaaaaaaaaaaaaaaaaaah,aaaaaaaaaah,aaaaaaaaaajajajajajajajahahahajahaja,aaaaah,aaaaargh,aaaag,aaaah,...,zvakaoma,zvlahos,zyampii,zyeth,zyme,zynga,zython,zzoegrimm,zzz,cyberbullying_type
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,age
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,not_cyberbullying
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,age
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ethnicity
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,other_cyberbullying
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,other_cyberbullying
28610,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,age
28611,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,not_cyberbullying
28612,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,age
28613,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,age